package com.programminghoch10.RotationControl

val rewriteLockedOrientation = mapOf(
    ROTATION_MODE.SCREEN_ORIENTATION_LANDSCAPE to ROTATION_MODE.SCREEN_ORIENTATION_SENSOR_LANDSCAPE,
    ROTATION_MODE.SCREEN_ORIENTATION_PORTRAIT to ROTATION_MODE.SCREEN_ORIENTATION_SENSOR_PORTRAIT,
    ROTATION_MODE.SCREEN_ORIENTATION_REVERSE_LANDSCAPE to ROTATION_MODE.SCREEN_ORIENTATION_SENSOR_LANDSCAPE,
    ROTATION_MODE.SCREEN_ORIENTATION_REVERSE_PORTRAIT to ROTATION_MODE.SCREEN_ORIENTATION_SENSOR_PORTRAIT,
)

val rewriteSensorOrientation = mapOf(
    ROTATION_MODE.SCREEN_ORIENTATION_SENSOR to ROTATION_MODE.SCREEN_ORIENTATION_FULL_SENSOR,
    ROTATION_MODE.SCREEN_ORIENTATION_USER to ROTATION_MODE.SCREEN_ORIENTATION_FULL_USER,
)

