
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
        restore-keys: gradle-cache-

    - name: Prepare files
      run: |
        chmod +x gradlew

    - name: Compile
      run: ./gradlew assembleDebug

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        path: '*/build/outputs/apk/debug/*-debug.apk'
        if-no-files-found: error
